_target_: dem.energies.aldanine_dipeptide_pseudoenergy.MaceAlDiForcePseudoEnergy

dimensionality: 2
device: ${trainer.accelerator}

plot_samples_epoch_period: 1

data_normalization_factor: 2.0
should_unnormalize: false

train_set_size: 100000
test_set_size: 2000
val_set_size: 2000 