pes_fn: "toy_polynomial"  #  six_hump_camel or toy_polynomial

diffusion:
  timesteps: 1000
  beta_start: 0.0001
  beta_end: 0.02

model:
  hidden_dim: 32

training:
  learning_rate: 0.001
  outer_iterations: 5
  inner_epochs: 500
  batch_size: 64
  n_samples: 1024
  lambda_pseudo_energy: 0.1

plotting:
  cutoff: 5
  percentile: 95

sampling:
  n_samples: 2000
