
defaults:
  - gad_default
  - _self_

_target_: dem.energies.double_well_pseudoenergy.DoubleWellPseudoEnergy

device: ${trainer.accelerator}

plot_samples_epoch_period: 1

dimensionality: 2

data_normalization_factor: 1.0

is_molecule: False

# GAD parameters
term_aggr: gad
gad_offset: 50.0
clip_energy: True
stitching: True
stop_grad_ev: True
div_epsilon: 1e-6
clamp_min: 0
clamp_max: null


override_energy_dummy: 1.0

train_set_size: 0 # 100000
test_set_size: 2000
val_set_size: 2000 