_target_: dem.energies.four_wells_energy.FourWellsEnergy

device: ${trainer.accelerator}

dimensionality: 2

plot_samples_epoch_period: 1

data_normalization_factor: 1.0

is_molecule: False

train_set_size: 1000 # 100000
test_set_size: 2000
val_set_size: 2000