defaults:
  - pseudo_default
  - _self_

# dem/energies/four_wells_pseudoenergy.py FourWellsPseudoEnergy
_target_: dem.energies.four_wells_pseudoenergy.FourWellsPseudoEnergy

device: ${trainer.accelerator}

dimensionality: 2

plot_samples_epoch_period: 1

data_normalization_factor: 1.0

is_molecule: False

train_set_size: 0 # 100000
test_set_size: 2000
val_set_size: 2000

