defaults:
  - pseudo_default
  - _self_

_target_: dem.energies.gmm_pseudoenergy.GMMPseudoEnergy

# Original GMM parameters
dimensionality: 2
n_mixes: 40
loc_scaling: 40
log_var_scaling: 1.0

device: ${trainer.accelerator}

plot_samples_epoch_period: 1

should_unnormalize: true
data_normalization_factor: 50
data_path_train: null

# Pseudo-energy specific parameters
energy_weight: 0.0
force_weight: 1.0
forces_norm: null # None=2, 1, or inf
force_exponent: 1
force_exponent_eps: 0
force_activation: 'tanh'
force_scale: 0.1
hessian_weight: 1.0
hessian_eigenvalue_penalty: 'and'
hessian_scale: 1.0
term_aggr: '1mmultfh'


train_set_size: 1000 # 100000
test_set_size: 2000
val_set_size: 2000
