# @package _global_

model:
  # populate buffer
  num_buffer_samples_to_generate_init: 512
  num_buffer_samples_to_generate_per_epoch: 512
  
  integrate_energy_batch_size: 32
  integrate_model_batch_size: -1

  # batch size during training
  num_samples_to_sample_from_buffer: 16

  # per sample in batch
  num_estimator_mc_samples: 24

  # used to generate samples (integrate) and W2 distance
  eval_batch_size: 24
  # negative log likelihood = augmented integration
  nll_batch_size: 24
  
  # if you reduce num_buffer_samples_to_generate_init, you need to reduce min_length
  buffer:
    min_sample_length: 16

energy:
  plotting_batch_size: 800